### ISSUE TITLE
Lots of CPU

### ISSUE THREAD

**Issue by ahcarter** [w1gx/govee-gateway#6]
Running on RaspberryPi 3 B+, pulling from three Govee thermohygrometers, and writing into local Influx every 90 seconds.

govee-gateway CPU percentage is like 60%, even when I nice it way up to like 19.
It never goes into sleep.  Am I doing something wrong or is this intended behavior? 

![Screenshot 2021-06-06 204500](https://user-images.githubusercontent.com/85463250/120956315-20ddba80-c708-11eb-8d08-87d28c7fba8b.png)

**Comment by w1gx** [comment]
It never sleeps more than 10ms in between scans (see main.cpp #104). What is your logInterval and verbosity in the config file? I think the default logInterval is 2, and that might be too high. I am running with verbosity 0 and logInterval 30 for 10 sensors, and my CPU percentage is usually pretty low:
![Screen Shot 2021-06-07 at 8 58 39 AM](https://user-images.githubusercontent.com/74331779/121021158-14d91380-c76f-11eb-8692-d0775733007e.png)
Upping the logInterval setting means that the data over this period is averaged out and transmitted over this period in seconds. If the problem persists, try running it with a higher verbosity and see If there's maybe a lot of other bluetooth traffic around you.

**Comment by w1gx** [comment]
I have not heard anything anymore, so I am closing the issue for now. Please reopen if you continue to run into this problem.
