### ISSUE TITLE
Compatibility with other Govee bluetooth temp/humidity sensors?

### ISSUE THREAD

**Issue by smatthew** [w1gx/govee-gateway#7]
Do you know if this is compatible with other Govee bluetooth temp/humidity sensors? Like the HS102?

**Comment by w1gx** [comment]
Sorry, I do not. I tested it only with the sensors I have here. But if you check out the Wiki I wrote for the BLE scanner (https://github.com/w1gx/govee-ble-scanner/wiki/Sniffing-BLE-advertising-packets), you can maybe try to figure out what data the HS102 transmits. Let me know how it goes.
