### ISSUE TITLE
Data to InfluxDB only when running in terminal

### ISSUE THREAD

**Issue by billjuv** [w1gx/govee-gateway#8]
I’ve got the program working for the most part, but can’t get it to continue to send data from my sensors to the InfluxDB. 

The service shows to be running…

pi@HomePi:/ $ sudo service govee-gateway status
* govee-gateway.service - govee-gateway service
     Loaded: loaded (/usr/local/lib/systemd/system/govee-gateway.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-10-27 22:20:39 MDT; 15h ago
   Main PID: 3985 (govee-gateway)
      Tasks: 1 (limit: 4915)
        CPU: 14h 29min 52.694s
     CGroup: /system.slice/govee-gateway.service
             `-3985 /usr/local/bin/govee-gateway

Oct 27 22:20:39 HomePi systemd[1]: Started govee-gateway service.

…but the only time it sends data to InfluxDB is if I start it in the terminal, passing along the .conf file via command line parameters (which only works from within the govee-gateway directory). As soon as the terminal quits, so does saving data to Influx. 

What am I missing here?

P.S. Also, what does the MA=2 signify?

Thank, Bill J

pi@HomePi:~/govee-gateway $ sudo ./deb/govee-gateway/usr/local/bin/govee-gateway ./build/release/govee-gateway -c /home/pi/govee-gateway/govee-gateway.conf

config is /home/pi/govee-gateway/govee-gateway.conf
Address mapping: E3:60:58:E0:A4:6E mapped to BASEMENT
Address mapping: E3:5E:CC:70:38:B7 mapped to CAMPER GALLEY
Address mapping: E3:5E:CC:70:FC:88 mapped to CHILLY BIN
Address mapping: E3:5E:CC:73:60:60 mapped to FREEZER
Checking connections...
InfluxDB host is 10.0.1.110...  ok.
running...
Data logged. Queue#:  1. GOVEE E3:60:58:E0:A4:6E - Temp=18.70C (65.66F), Hum=29.65%, Bat=94%, RSSI= -51dBm, MA=2
Data logged. Queue#:  1. GOVEE E3:5E:CC:73:60:60 - Temp=-17.22C (1.00F), Hum=77.29%, Bat=63%, RSSI= -67dBm, MA=2
Data logged. Queue#:  1. GOVEE E3:5E:CC:70:38:B7 - Temp=19.11C (66.40F), Hum=27.69%, Bat=100%, RSSI= -71dBm, MA=2
Data logged. Queue#:  1. GOVEE E3:5E:CC:70:FC:88 - Temp=15.87C (60.57F), Hum=28.70%, Bat=78%, RSSI= -63dBm, MA=2

**Comment by w1gx** [comment]
the service will use the conf file in /etc: 
/etc/govee-gateway.conf 

please make sure you have your configuration in there.

As for the MA, if you look into the code you will see I documented it there. It's a "mysterious attribute", I don't know what it stands for.

**Comment by billjuv** [comment]
Thanks, that's what I needed! 

I'm still pretty new at this stuff and "a config file, which is located in the root of the project folder" wasn't enough of a hint. Great program... should suit my needs well. Thanks

**Comment by w1gx** [comment]
good point - I just added it to the README. I am closing this ticket, but let me know if you run into any other issues.
